### ISSUE TITLE
Some bugs and suggestions

### ISSUE THREAD

**Issue by Yesboy77** [Adriftus-Studios/network-script-data#118]
Hello, I made a video for you guys about some bugs that I've found and some suggestions that I have for the server

https://youtu.be/41_SzxRBvRY

**Comment by BehrRiley** [comment]
I've added the suggestions made regarding the `/balance`'s crazy output number; it will now be rounded to the second decimal place.

Additionally, there's some complicated logic behind our custom crafting mechanics, I've made it so that it *should* output the enchantments on the item now after crafting and combining items in anvils.

Thanks for the suggestions 🥇
