### ISSUE TITLE
[BORKED]claiming_protection_events error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#123]
> **Error Message**:

`Property 'MaterialAge' does not describe the input object.`

> **Script Information**:

Script Name:  `claiming_protection_events`

Script Reference:  [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1180)

Script Line: 1180

> **Player Attached**:

`Cryotea` / `(dada31c2-b0d8-4ac6-ad29-ffdcd3f0f44c`

**Comment by Ph4i1ur3** [comment]
I have 0 idea wtf this could even be... lol

**Comment by BehrRiley** [comment]
The problem is associated with an invalid material being converted here, which would make sense after checking here:
`<script[claiming_protection_events].data_key[farmables]>` returns the key here:
`farmables: pumpkins|carrots|wheat|beetroots|potatoes|cocoa|sugar_cane|kelp_plant|melon`
`pumpkins` is not a valid item or material

**Comment by Ph4i1ur3** [comment]
I think its due to checking the age on some of those materials that do not have an age property (like sugarcane)

Fixed this particular scenario in #131
