### ISSUE TITLE
[BORKED]combat_log_events error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#146]
> **Error Message**:

`Tag <player.flag[combat].expiration.in_seconds> is invalid!`

> **Script Information**:

Script Name:  `combat_log_events`

Script Reference:  [`survival/./repo_link/combat_log.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/combat_log.dsc#L20)

Script Line: 20

> **Player Attached**:

`GavinPlayzMC` / `(f2d5fafe-3900-46c9-946b-81475553f6c7`

**Comment by BehrRiley** [comment]
reference of the relevant script:
```yml
    on delta time secondly every:1:
      - foreach <server.online_players_flagged[combat]> as:player:
        - adjust <queue> linked_player:<[player]>
        - if <player.flag[combat].expiration.in_seconds> <= 1:
          - wait 1s
          - narrate "<&b>You are no longer in combat."
```
this is the result of not verifying whether a script exists first, or not. I always recommend verifying the existence of a flag before attempting to read anything of it first.
- instead of attempting to read a flag's expiration that may or may not exist and converting that duration into seconds, and then verifying it is less than one, i would recommend either:
  - instead check the exact expiration and verify if the `.flag[combat].is_expired` as opposed to ruling out the last `999ms` in the case that the expiration is less than a single second
  - validate the flag exists first with a `<player.has_flag[combat]> &&` prior to this check
- instead of using a the `every` switch here, remove it entirely since it's default in favor of `on delta time secondly`
- **don't adjust the queue's linked player when you can just use the player's definition as the entitytag**. Replace `<player>` with `<[player]>` and don't adjust queues.
- remove the `wait` in this script; it is going to loop across every player every second. for example:
  - if 60 players are online flagged `combat` and all of their flag's expiration has reduced less than one second, it would take 59 seconds before the 60th player in this list would receive notification that he wasn't in combat because the `foreach` is looping across each individual player and waiting a second before narrating.

**Comment by Eutherin** [comment]
will <player.flag[combat].is_expired> be invalid if the players flag has expired? or does a flag revert to false instead of null after expiry?
