### ISSUE TITLE
[BORK] Parrots follow players to spawn and persist through death

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#42]
![image](https://user-images.githubusercontent.com/25861695/89767891-ac1dfd80-daaf-11ea-975f-2670ab99a9ec.png)
TL;DR 
His parrots wouldn't get off his shoulder even in dead in the survival world, so he deposited them at spawn.

**Comment by BehrRiley** [comment]
Don't need a TL;DR: If someone can't read the entirety of an issue they shouldn't bother getting involved in attempting to resolve it

> I would die and they would stay on the shoulders of my character as said character did the falling to the side in the death screen

This last part doesn't sound relevant unless they're implying they were dying by death - the only relevance this includes is if the player was implying they were doing any of the following that dismounts a parrot:
- Jumps down natural terrain
  - Natural terrain dismount is any coordinate height > 0.75 < 0.5 blocks tall
- player takes damage
- head is submerged in lava
- submerges the player's feet into water with a water level of 4 or higher

Additional notes:
- The only event that could remotely manage this is the `Entity Spawns` event, with the `context.reason` returning `SHOULDER_ENTITY`, determined when an entity is spawned because: `When an entity is spawned as a result of the entity it is being perched on jumping or being damaged`
- There are no global scripts tied to `entity spawn`
- There are three scripts in Survival that utilize the `entity spawn` event:
  - `claim_system_upgrade_spawn_prevention` located at `global_systems\chunk_claim_protection.dsc` has the event header `on entity spawns because natural`
  - `mob_spawning_system_events` located at `global_systems\mob_spawn_system.dsc` has the event header `on entity spawns in:mainland`
  - `spawn_world_protection` located at `spawn_scripts\spawn_protection.dsc` has the event header `on entity spawns in:spawn` but also verifies `if <context.reason> == NATURAL` before cancelling the event
 - Paper has a configuration key `world-settings.default.parrots-are-unaffected-by-player-movement` which is set to `false` in Survival's `paper.yml`

**Comment by Eutherin** [comment]
Does not seem to be a reoccurring issue.
